name: publish coverage summary
description: publish coverage summary 
runs:
  using: composite
  steps:
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.13
      with:
        reports: coverage.cobertura.xml
        targetdir: coveragereport
        reporttypes: MarkdownSummaryGithub
        tag: "${{ github.run_number }}_${{ github.run_id }}"

    - name: publish run summary
      shell: bash
      run: cat coveragereport/SummaryGithub.md >$GITHUB_STEP_SUMMARY
