name: Workflow PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        NUGET_XMLDOC_MODE: skip
    steps:
        - name: build
          uses: ./.github/actions/task-group-build.yml
        
        - name: test
          uses: ./.github/actions/task-group-test-coverage.yml
        
        - name: publish result
          uses: ./.github/actions/task-group-publish-coverage-comments.yml    